### ISSUE TITLE
 error when making commit

### ISSUE THREAD

**Issue by RodrigoGoncalvesDev** [Dathin/JHusky#7]
error: cannot spawn .husky/pre-commit: No such file or directory

**Comment by Dathin** [comment]
Hey Rodrigo, sorry for delay. Were you already able to solve your issue?

Can you check if this exact file path already exists? You could probably `cat .husky/pre-commit`. 

If it does not and you want to create one you could use `mvn jhusky:add -DhookPath=.husky/pre-commit -Dcommand="mvn clean test"`.

If you don't want to do it then we can debug it further, can you share steps you did to reproduce this issue?

**Comment by bwgjoseph** [comment]
Hi @Dathin, I am testing this plugin out but I am getting the same error message as the author, and didn't want to create new issue.

I installed by running `mvnw jhusky:install -Ddirectory=.husky` and then added the `pre-commit` hook using this command `mvnw jhusky:add -DhookPath=.husky/pre-commit -Dcommand="mvnw spotless:check"`

![image](https://user-images.githubusercontent.com/37484538/193465681-dfbb1dea-06d2-4814-a44b-0733c39995ed.png)

Now, when I tried to perform a commit, it throws the error.

![image](https://user-images.githubusercontent.com/37484538/193465746-f7649fae-5c00-4643-b9dd-4acb052c7415.png)

Is there any steps that I've done wrongly?

Thanks!

**Comment by bwgjoseph** [comment]
Anyway, I think I figured out after some [googling](https://github.com/conventional-changelog/standard-version/issues/254#issuecomment-424669323)

So after added `#!/bin/sh` manually, it works.

But it relies on `mvn` and not `mvnw`. This is likely a separate issue, will probably create this later on

**Comment by Dathin** [comment]
Hello @bwgjoseph, I'm glad that it woked for you.

Please try `./mvnw spotless:check`
